# https://docs.microsoft.com/azure/devops/pipelines/yaml-schema

pr: none
trigger:
  batch: true
  branches:
    include:
      - azure
      - master
      - release/*

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: '*Tests/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration Release --output publish'
    zipAfterPublish: false

- task: OctopusPack@4
  displayName: 'Create Octopus package'
  inputs:
    PackageId: 'WhyNotEarth.Meredith.App'
    PackageFormat: 'NuPkg'
    PackageVersion: '$(GitAssemblyInformationalVersion)'
    SourcePath: 'publish'
    OutputPath: 'OctopusPackages'

- task: NuGetCommand@2
  displayName: 'Push NuGet package to Octopus feed'
  inputs:
    command: push
    packagesToPush: 'OctopusPackages/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'meredith-core/OctopusFeed'

- task: OctopusCreateRelease@3
  displayName: 'Create Octopus Release'
  inputs:
    OctoConnectedServiceName: 'OctopusServer'
    ProjectName: 'Meredith'
    ReleaseNumber: '$(GitAssemblyInformationalVersion)'
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      Channel: 'production'
    ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
      Channel: 'Default'
    AdditionalArguments: "--packageversion=$(GitAssemblyInformationalVersion)"